<?php
/**
 * CoreShop
 *
 * LICENSE
 *
 * This source file is subject to the GNU General Public License version 3 (GPLv3)
 * For the full copyright and license information, please view the LICENSE.md and gpl-3.0.txt
 * files that are distributed with this source code.
 *
 * @copyright  Copyright (c) 2015-2016 Dominik Pfaffenbauer (https://www.pfaffenbauer.at)
 * @license    http://www.coreshop.org/license     GNU General Public License version 3 (GPLv3)
 */

\CoreShop\Tool::loadController("Checkout");

/*
 * Example of how to overwrite a CoreShop Controller
 */

class CheckoutController extends CoreShop_CheckoutController {

    public function init()
    {
        parent::init();
    }

    public function confirmationAction()
    {
        //Overwrite the confirmationAction here
        parent::confirmationAction(); // TODO: Change the autogenerated stub
    }
}
